services:
  flask:
    image: flaskapp:v1
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
